In [1]:
import pandas as pd
import numpy as np
import requests
import json
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics i
mport accuracy_score

In [79]:
pop_metrics = pd.DataFrame()

for year in range(2010,2017):
    file_path = "data/" + str(year) + "_final.csv"
    temp = pd.read_csv(file_path)
    
    del temp['county']
    del temp['Total Pop']

    temp = temp.rename(columns={'NAME': 'COUNTY'})
    temp["COUNTY"] = temp["COUNTY"].str.split(' County', expand=True)
    temp['COUNTY'] = temp['COUNTY'].str.upper()

    temp['Year'] = year

    temp.set_index(['Year', 'COUNTY'], inplace=True)
    pop_metrics = pop_metrics.append(temp)

pop_metrics.head()

               % Foreign Born  % Overseas Move Past Year  Birthrate Past Year  \
Year COUNTY
2010 MERCED         24.811028                   0.246910             8.157812
     MODOC           6.600729                   0.000000             5.335534
     MONO           18.439410                   0.640058             2.052350
     MONTEREY       30.136832                   0.921865             6.379867
     NAPA           22.498900                   0.928751             5.881788

               % School Aged  Ave HH Size  % Not Enrolled  \
Year COUNTY
2010 MERCED        26.901982     3.202760    79339.182347
     MODOC         20.041645     2.154720     3868.818182
     MONO          19.144193     2.160188     5906.093914
     MONTEREY      22.258274     2.830233   143009.584730
     NAPA          19.728312     2.445088    48270.446948

               % School-Aged Below Poverty Line
Year COUNTY
2010 MERCED                           72.468603
     MODOC                            84.000000
     MONO                             62.283997
     MONTEREY                         55.497971
     NAPA                             47.073281